backend:
  name: github
  repo: jakehorton/jake_blog
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
